apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nid-soc
  namespace: nid-soc
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts: ["soc.example.com", "api.soc.example.com"]
      secretName: nid-soc-tls
  rules:
    - host: soc.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nid-soc-frontend
                port:
                  name: http
    - host: api.soc.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nid-soc-api
                port:
                  name: http
